/**
 * Reads public/data/metro.geojson and emits a SQL dump (INSERT statements only) to
 * stdout (or to the file given as the first argument). The dump is meant to
 * be piped into wrangler:
 *
 *   npx tsx scripts/import-metro-geojson.ts data/metro.sql
 *   npx wrangler d1 execute DTPMGEO --local --file=data/metro.sql
 *
 * The destination table must already exist (apply the drizzle migration first:
 *   npm run db:dtpmgeo:apply:local).
 *
 * Each feature becomes one row in `metro_features` with `kind`, `geometry` (JSON)
 * and `properties` (JSON).
 *
 * Geometry types:
 * - LineString -> kind "line"
 * - Point -> kind "station"
 */
import { createWriteStream } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

type GeoJsonFeature = {
	type: "Feature";
	geometry: { type: string };
	properties?: Record<string, unknown> | null;
};

type FeatureCollection = {
	type: "FeatureCollection";
	features: GeoJsonFeature[];
};

const INPUT_PATH = resolve(process.cwd(), "public/data/metro.geojson");

const outPath = process.argv[2];
const out = outPath ? createWriteStream(outPath) : process.stdout;
const log = (msg: string) => process.stderr.write(`${msg}\n`);

function sqlEscape(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

function kindOf(feature: GeoJsonFeature): string {
	if (feature.geometry.type === "LineString") return "line";
	if (feature.geometry.type === "Point") return "station";
	return feature.geometry.type;
}

async function main() {
	log(`Reading ${INPUT_PATH}…`);
	const raw = await readFile(INPUT_PATH, "utf8");
	const fc = JSON.parse(raw) as FeatureCollection;
	if (fc.type !== "FeatureCollection" || !Array.isArray(fc.features)) {
		throw new Error("Input is not a GeoJSON FeatureCollection");
	}

	log(`Parsed ${fc.features.length} features. Emitting SQL…`);

	out.write("-- Auto-generated by scripts/import-metro-geojson.ts\n");
	out.write("DELETE FROM metro_features;\n");

	let written = 0;
	for (const feature of fc.features) {
		const kind = sqlEscape(kindOf(feature));
		const geometry = sqlEscape(JSON.stringify(feature.geometry));
		const properties = sqlEscape(JSON.stringify(feature.properties ?? {}));
		out.write(
			`INSERT INTO metro_features (kind, geometry, properties) VALUES (${kind}, ${geometry}, ${properties});\n`,
		);
		written++;
		if (written % 500 === 0) log(`  ${written}/${fc.features.length}`);
	}

	if (outPath) {
		await new Promise<void>((res) =>
			(out as ReturnType<typeof createWriteStream>).end(res),
		);
	}
	log(`Done. Wrote ${written} rows.`);
}

main().catch((err) => {
	log(`Error: ${err instanceof Error ? err.message : String(err)}`);
	process.exit(1);
});
