/**
 * Reads public/data/frequencies.geojson and emits SQL INSERT statements.
 * Note: This is NOT a GeoJSON file - it's a flat key-value object.
 * Key format: "{busRoute}|{direction}|{origin}"
 * Usage:
 *   npx tsx scripts/import-frequencies.ts data/frequencies.sql
 *   npx wrangler d1 execute DTPMGEO --local --file=data/frequencies.sql
 */
import { createWriteStream } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

type FrequencyData = {
	mean_headway_s: number;
	samples: number;
};

type FrequencyMap = Record<string, FrequencyData>;

const INPUT_PATH = resolve(process.cwd(), "public/data/frequencies.geojson");
const outPath = process.argv[2];
const out = outPath ? createWriteStream(outPath) : process.stdout;
const log = (msg: string) => process.stderr.write(`${msg}\n`);

function sqlEscape(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

function parseRouteKey(key: string): {
	bus_route: string;
	direction: number;
	origin: string;
} {
	const parts = key.split("|");
	return {
		bus_route: parts[0] ?? key,
		direction: parseInt(parts[1] ?? "0", 10),
		origin: parts.slice(2).join("|"),
	};
}

async function main() {
	log(`Reading ${INPUT_PATH}…`);
	const raw = await readFile(INPUT_PATH, "utf8");
	const data = JSON.parse(raw) as FrequencyMap;
	const entries = Object.entries(data);

	log(`Parsed ${entries.length} frequency records. Emitting SQL…`);
	out.write("-- Auto-generated by scripts/import-frequencies.ts\n");
	out.write("DELETE FROM bus_frequencies;\n");

	let written = 0;
	for (const [key, value] of entries) {
		const { bus_route, direction, origin } = parseRouteKey(key);
		const values = [
			sqlEscape(key),
			sqlEscape(bus_route),
			direction,
			sqlEscape(origin),
			value.mean_headway_s,
			value.samples,
		];
		out.write(
			`INSERT INTO bus_frequencies (route_key, bus_route, direction, origin, mean_headway_seconds, samples) VALUES (${values.join(", ")});\n`,
		);
		written++;
		if (written % 500 === 0) log(`  ${written}/${entries.length}`);
	}

	if (outPath) {
		await new Promise<void>((res) =>
			(out as ReturnType<typeof createWriteStream>).end(res),
		);
	}
	log(`Done. Wrote ${written} rows.`);
}

main().catch((err) => {
	log(`Error: ${err instanceof Error ? err.message : String(err)}`);
	process.exit(1);
});
