/**
 * Reads public/data/comunas_rm.geojson and emits SQL INSERT statements.
 * Usage:
 *   npx tsx scripts/import-comunas.ts data/comunas.sql
 *   npx wrangler d1 execute DTPMGEO --local --file=data/comunas.sql
 */
import { createWriteStream } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

type GeoJsonFeature = {
	type: "Feature";
	geometry: { type: string; coordinates: unknown };
	properties: Record<string, unknown> | null;
};

type FeatureCollection = {
	type: "FeatureCollection";
	features: GeoJsonFeature[];
};

const INPUT_PATH = resolve(process.cwd(), "public/data/comunas_rm.geojson");
const outPath = process.argv[2];
const out = outPath ? createWriteStream(outPath) : process.stdout;
const log = (msg: string) => process.stderr.write(`${msg}\n`);

function sqlEscape(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

async function main() {
	log(`Reading ${INPUT_PATH}…`);
	const raw = await readFile(INPUT_PATH, "utf8");
	const fc = JSON.parse(raw) as FeatureCollection;
	if (fc.type !== "FeatureCollection" || !Array.isArray(fc.features)) {
		throw new Error("Input is not a GeoJSON FeatureCollection");
	}

	log(`Parsed ${fc.features.length} features. Emitting SQL…`);
	out.write("-- Auto-generated by scripts/import-comunas.ts\n");
	out.write("DELETE FROM comunas;\n");

	let written = 0;
	for (const feature of fc.features) {
		const p = feature.properties ?? {};
		const values = [
			p.objectid ?? "NULL",
			p.cod_comuna ?? "NULL",
			p.codregion ?? "NULL",
			p.Comuna ? sqlEscape(String(p.Comuna)) : "NULL",
			p.Provincia ? sqlEscape(String(p.Provincia)) : "NULL",
			p.Region ? sqlEscape(String(p.Region)) : "NULL",
			p.dis_elec ?? "NULL",
			p.cir_sena ?? "NULL",
			p.st_area_sh ?? "NULL",
			p.st_length_ ?? "NULL",
			sqlEscape(JSON.stringify(feature.geometry)),
		];
		out.write(
			`INSERT INTO comunas (objectid, cod_comuna, cod_region, nombre_comuna, provincia, region, dis_elec, cir_sena, shape_area, shape_length, geometry) VALUES (${values.join(", ")});\n`,
		);
		written++;
	}

	if (outPath) {
		await new Promise<void>((res) =>
			(out as ReturnType<typeof createWriteStream>).end(res),
		);
	}
	log(`Done. Wrote ${written} rows.`);
}

main().catch((err) => {
	log(`Error: ${err instanceof Error ? err.message : String(err)}`);
	process.exit(1);
});
