/**
 * Reads public/data/ciclovias.geojson and emits SQL INSERT statements.
 * Usage:
 *   npx tsx scripts/import-ciclovias.ts data/ciclovias.sql
 *   npx wrangler d1 execute DTPMGEO --local --file=data/ciclovias.sql
 */
import { createWriteStream } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

type GeoJsonFeature = {
	type: "Feature";
	geometry: { type: string; coordinates: unknown };
	properties: Record<string, unknown> | null;
};

type FeatureCollection = {
	type: "FeatureCollection";
	features: GeoJsonFeature[];
};

const INPUT_PATH = resolve(process.cwd(), "public/data/ciclovias.geojson");
const outPath = process.argv[2];
const out = outPath ? createWriteStream(outPath) : process.stdout;
const log = (msg: string) => process.stderr.write(`${msg}\n`);

function sqlEscape(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

async function main() {
	log(`Reading ${INPUT_PATH}…`);
	const raw = await readFile(INPUT_PATH, "utf8");
	const fc = JSON.parse(raw) as FeatureCollection;
	if (fc.type !== "FeatureCollection" || !Array.isArray(fc.features)) {
		throw new Error("Input is not a GeoJSON FeatureCollection");
	}

	log(`Parsed ${fc.features.length} features. Emitting SQL…`);
	out.write("-- Auto-generated by scripts/import-ciclovias.ts\n");
	out.write("DELETE FROM ciclovias;\n");

	let written = 0;
	for (const feature of fc.features) {
		const p = feature.properties ?? {};
		const values = [
			p.FID ?? "NULL",
			p.name ? sqlEscape(String(p.name)) : "NULL",
			p.folderpath ? sqlEscape(String(p.folderpath)) : "NULL",
			p.popupinfo ? sqlEscape(String(p.popupinfo)) : "NULL",
			p.longitud ?? "NULL",
			p.Shape__Length ?? "NULL",
			sqlEscape(JSON.stringify(feature.geometry)),
		];
		out.write(
			`INSERT INTO ciclovias (fid, name, folderpath, popupinfo, longitud_km, shape_length_m, geometry) VALUES (${values.join(", ")});\n`,
		);
		written++;
		if (written % 200 === 0) log(`  ${written}/${fc.features.length}`);
	}

	if (outPath) {
		await new Promise<void>((res) =>
			(out as ReturnType<typeof createWriteStream>).end(res),
		);
	}
	log(`Done. Wrote ${written} rows.`);
}

main().catch((err) => {
	log(`Error: ${err instanceof Error ? err.message : String(err)}`);
	process.exit(1);
});
