/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EodRouteImport } from './routes/eod'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiComparadorStatsRouteRouteImport } from './routes/api/comparador/stats.route'

const EodRoute = EodRouteImport.update({
  id: '/eod',
  path: '/eod',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComparadorStatsRouteRoute = ApiComparadorStatsRouteRouteImport.update({
  id: '/api/comparador/stats',
  path: '/api/comparador/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparador': typeof ComparadorRoute
  '/eod': typeof EodRoute
  '/api/comparador/stats': typeof ApiComparadorStatsRouteRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparador': typeof ComparadorRoute
  '/eod': typeof EodRoute
  '/api/comparador/stats': typeof ApiComparadorStatsRouteRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparador': typeof ComparadorRoute
  '/eod': typeof EodRoute
  '/api/comparador/stats': typeof ApiComparadorStatsRouteRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparador'
    | '/eod'
    | '/api/comparador/stats'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comparador' | '/eod' | '/api/comparador/stats' | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/comparador'
    | '/eod'
    | '/api/comparador/stats'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparadorRoute: typeof ComparadorRoute
  EodRoute: typeof EodRoute
  ApiComparadorStatsRouteRoute: typeof ApiComparadorStatsRouteRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/eod': {
      id: '/eod'
      path: '/eod'
      fullPath: '/eod'
      preLoaderRoute: typeof EodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comparador/stats': {
      id: '/api/comparador/stats'
      path: '/api/comparador/stats'
      fullPath: '/api/comparador/stats'
      preLoaderRoute: typeof ApiComparadorStatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparadorRoute: ComparadorRoute,
  EodRoute: EodRoute,
  ApiComparadorStatsRouteRoute: ApiComparadorStatsRouteRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
