/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KvRouteImport } from './routes/kv'
import { Route as EodRouteImport } from './routes/eod'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCacheClearRouteImport } from './routes/api/cache-clear'

const KvRoute = KvRouteImport.update({
  id: '/kv',
  path: '/kv',
  getParentRoute: () => rootRouteImport,
} as any)
const EodRoute = EodRouteImport.update({
  id: '/eod',
  path: '/eod',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCacheClearRoute = ApiCacheClearRouteImport.update({
  id: '/api/cache-clear',
  path: '/api/cache-clear',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eod': typeof EodRoute
  '/kv': typeof KvRoute
  '/api/cache-clear': typeof ApiCacheClearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eod': typeof EodRoute
  '/kv': typeof KvRoute
  '/api/cache-clear': typeof ApiCacheClearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eod': typeof EodRoute
  '/kv': typeof KvRoute
  '/api/cache-clear': typeof ApiCacheClearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eod' | '/kv' | '/api/cache-clear'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eod' | '/kv' | '/api/cache-clear'
  id: '__root__' | '/' | '/eod' | '/kv' | '/api/cache-clear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EodRoute: typeof EodRoute
  KvRoute: typeof KvRoute
  ApiCacheClearRoute: typeof ApiCacheClearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kv': {
      id: '/kv'
      path: '/kv'
      fullPath: '/kv'
      preLoaderRoute: typeof KvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eod': {
      id: '/eod'
      path: '/eod'
      fullPath: '/eod'
      preLoaderRoute: typeof EodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache-clear': {
      id: '/api/cache-clear'
      path: '/api/cache-clear'
      fullPath: '/api/cache-clear'
      preLoaderRoute: typeof ApiCacheClearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EodRoute: EodRoute,
  KvRoute: KvRoute,
  ApiCacheClearRoute: ApiCacheClearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
